version: '3.7'
services:

    step-app-calculator-yii2-php-fpm:
        image: ${REGISTRY}/${PHP_FMP_CONTAINER_NAME}:${IMAGE_TAG}
        volumes:
            - .:/app

    step-app-calculator-yii2-php-cli:
        image: ${REGISTRY}/${PHP_CLI_CONTAINER_NAME}:${IMAGE_TAG}
        volumes:
            - .:/app

    step-app-calculator-yii2-nginx:
        image: ${REGISTRY}/${NGINX_CONTAINER_NAME}:${IMAGE_TAG}
        ports:
            - ${APP_WEB_PORT}:80
        volumes:
            - .:/app